### ISSUE TITLE
subm_templates: show validation messages on mouseover in the Feature

### ISSUE THREAD

**Issue by olgamelnichuk** [EBIBioStudies/BioStudyUISub#76]
Every edit box in Feature (grid or list) which has non empty list of validation rules should show error messages on mouseover.

**Comment by hqcasanova** [comment]
What do you mean exactly by edit box? It seems the features on the right-hand side pane do show an error message on hover, being revealed with a translateX effect. However, this only happens when hovering over the ">" symbol right next to the counter.

![screen shot 2017-08-23 at 09 47 55](https://user-images.githubusercontent.com/6626603/29607305-b9acdb50-87e8-11e7-89ee-e398a5ae7537.png)

Are you saying that you want to extend the hovering area that would trigger that message reveal effect?

**Comment by olgamelnichuk** [comment]
It's not an error message. It's just a description of what the grid/list of values is about..
In the current production version we have error messages shown on mouse over for each red colored box

<img width="437" alt="screen shot 2017-08-23 at 10 16 15" src="https://user-images.githubusercontent.com/547240/29608698-dea009a6-87ec-11e7-9dde-5914383fbb6b.png">

**Comment by hqcasanova** [comment]
Ah! Ok. I take that, since an error is being shown on hover already in the production version, this issue no longer applies? Should we close it?

**Comment by olgamelnichuk** [comment]
Nope. As subm_templates has completely new UI and model it's not implemented yet here, but should be

**Comment by hqcasanova** [comment]
Fixed in PR #112
